name: Image to ECR

on:
  push:
    branches:
      - main


jobs:
  build-tag-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
          mask-password: 'true'
          
    - name: path
      run: |
        cd --path-to-the-reposetory-inside-__work dir--

    - name: Build Image
      run: |
        export v=--public-ecr-repo-url--
        docker buildx build -t $v -f dockerfile .      
    
    - name: Push Image
      run: |
        export v=--public-ecr-repo-url--
        docker push $v:latest
